name: IDEme

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      go-version: [1.14, 1.15]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Format
        run: |
          go fmt && go vet
      - name: Build
        run: |
          go build -o .
      - name: Test
        run: |
          go test
