name: ideme

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.14", "1.15"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Clean
        run: |
          go clean -cache
      - name: Format
        run: |
          go fmt
      - name: Vet
        run: |
          go vet
      - name: Test
        run: |
          go test
